# Numpy 패키지

## Numpy 패키지 설치 및 import

In [1]:
# numpy패키지 설치

In [2]:
pip install numpy  

In [3]:
import numpy as np #np라는 이름으로 numpy를 사용

# 배열 vs. 리스트 비교

In [42]:
a = np.array([[1,2],[3,4]]) #array 배열

In [43]:
b = [[1,2],[3,4]] # 리스트

In [44]:
a

array([[1, 2],
       [3, 4]])

In [45]:
b

[[1, 2], [3, 4]]

In [46]:
a[1,1]

4

In [47]:
b[1][1]

4

# 배열(Array) 만들기

### 1차원 배열

In [4]:
#Array 정의하기 및 사용

In [5]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [6]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [7]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [8]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [9]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [10]:
arr2.shape

(5,)

In [11]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [12]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [13]:
arr3.shape #1차월 5개요소

(5,)

In [14]:
arr3.dtype

dtype('float64')

### 2차원 배열

In [15]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
arr4.shape

(4, 3)

### 3차원 배열

In [17]:
arr5=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
                 [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

In [18]:
type(arr5)

numpy.ndarray

In [19]:
arr5.shape

(2, 4, 3)

### 기타 배열 만드는 함수

In [20]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만듬

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((3,5))[0,0]

0.0

In [18]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만듬

In [19]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만듬
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가짐

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
# (N, N) shape을 특정값으로 채움, (2,2)를 7로 채움
np.full((2,2),7) 

array([[7, 7],
       [7, 7]])

In [25]:
#(N, N) shape의 단위 행렬(Unit Matrix)을 생성
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성
#주의해야 할 것은 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어가 있음
np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.36356552e-321],
       [1.01855798e-312, 0.00000000e+000]])

In [27]:
# arange로 1부터 10 미만의 범위에서 1씩 증가하는 배열 생성
# 배열의 shape을 (3, 3)으로 지정
a = np.arange(1, 10).reshape(3, 3)

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Array 연산

In [34]:
#Array 연산

In [35]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr1.shape

(2, 3)

In [37]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [38]:
arr2.shape

(2, 3)

In [39]:
#Array 덧셈
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [40]:
#Array 뺄셈
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [41]:
#Array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [42]:
#Array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 다른 크기의 array 연산

In [43]:
#arrar의 브로드 캐스트

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr1.shape

(2, 3)

In [46]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [47]:
arr3.shape 

(3,)

In [48]:
arr1 + arr3 #서로 다른 크기 연산가능. [10,11,12],[10,11,12]로 확장되어 계산

array([[11, 13, 15],
       [14, 16, 18]])

In [49]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [50]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

### Array 의 인덱싱

In [62]:
#Array 인덱싱

In [63]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# 0번째 요소
arr1[0]

0

In [65]:
# 3번째 요소
arr1[3]

3

In [66]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [67]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# 배열 인덱싱은 다차원 배열의 각 차원에 대해 가능
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [70]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [71]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [72]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

In [73]:
# 행의 순서 변경하기
arr2[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### Array Boolean을 활용한 인덱싱

In [106]:
#Array Boolean 인덱싱

In [107]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4) #8행 4열로 난수 채움
data

array([[ 0.83832538,  1.3949089 ,  1.13605548, -0.77862368],
       [ 0.18496071, -0.13105005,  0.60977164, -1.97205033],
       [-1.12005276,  0.6260243 , -0.78348917, -1.26948992],
       [-0.99382664, -0.93686718,  0.28091162,  1.10067739],
       [-0.12847909,  0.91109623, -1.03994093,  1.03078359],
       [ 1.34304146,  2.93240055, -1.62752494,  0.05705258],
       [-0.8285819 ,  1.4099084 , -0.2682601 , -1.22714378],
       [-0.47610564,  1.67728024,  0.46977785, -0.22251702]])

In [108]:
data = np.random.randint(0,100,size=(8,4)) #8행 4열로  0부터 100사이의 정수로 채움
data

array([[51, 65, 12, 33],
       [58, 87, 81, 69],
       [80,  8, 47,  5],
       [88, 24, 47, 35],
       [17, 88, 64, 57],
       [30, 83, 93, 34],
       [ 7, 97, 62, 11],
       [93, 65, 64, 20]])

In [109]:
type(data)

numpy.ndarray

In [110]:
data.shape

(8, 4)

In [125]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 50보다 작은 요소의 boolean 값은 다음과 같다.
data[:,0] < 50

array([False, False, False, False,  True,  True,  True, False])

In [126]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 50보다 작은 행을 구한다.
data[data[:,0]<50,:]

array([[17, 88, 64, 57],
       [30, 83, 93, 34],
       [ 7, 97, 62, 11]])

In [127]:
# 0번째 열의 값이 50보다 작은 행의 2,3번째 열 값
data[data[:,0]<50,2:4]

array([[64, 57],
       [93, 34],
       [62, 11]])

In [128]:
#0번째 열의 값이 50보다 작은 행의 2,3번째 열값에 0을 대입
data[data[:,0]<50,2:4] = 0
data

array([[51, 65, 12, 33],
       [58, 87, 81, 69],
       [80,  8, 47,  5],
       [88, 24, 47, 35],
       [17, 88,  0,  0],
       [30, 83,  0,  0],
       [ 7, 97,  0,  0],
       [93, 65, 64, 20]])

In [115]:
#boolean을 활용한 인덱싱
arr2[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [5]:
import numpy as np

In [6]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [7]:
names.shape

(8,)

In [10]:
names[0,]

'Beomwoo'

In [9]:
names[4,]

'Lee'

In [120]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [121]:
data[names_Beomwoo_mask,:]

array([[51, 65, 12, 33],
       [58, 87, 81, 69],
       [30, 83, 93, 34],
       [93, 65, 64, 20]])

In [122]:
names == 'Kim'

array([False, False,  True, False, False, False, False, False])

In [123]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim',:]

array([[80,  8, 47,  5]])

In [124]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'),:]

array([[80,  8, 47,  5],
       [ 7, 97, 62, 11]])

###  연산에 활용하는 Numpy함수들

### 하나의 array에 적용

In [106]:
#하나의 arrary에 적용되는 함스

In [129]:
arr1 = np.random.randint(-100,100,size=(4,3)) #4행 3열로 난수 채움
arr1

array([[ 10, -88, -70],
       [ 45, -34, -62],
       [-14, -53, -41],
       [  9, -26, -51]])

In [130]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[10, 88, 70],
       [45, 34, 62],
       [14, 53, 41],
       [ 9, 26, 51]])

In [131]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

C:\Users\Park MinJu\AppData\Local\Temp\ipykernel_18448\520945400.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[3.16227766,        nan,        nan],
       [6.70820393,        nan,        nan],
       [       nan,        nan,        nan],
       [3.        ,        nan,        nan]])

In [132]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[ 100, 7744, 4900],
       [2025, 1156, 3844],
       [ 196, 2809, 1681],
       [  81,  676, 2601]], dtype=int32)

In [133]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr1)

array([[2.20264658e+04, 6.05460190e-39, 3.97544974e-31],
       [3.49342711e+19, 1.71390843e-15, 1.18506486e-27],
       [8.31528719e-07, 9.60268005e-24, 1.56288219e-18],
       [8.10308393e+03, 5.10908903e-12, 7.09547416e-23]])

In [134]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
np.log(arr1)

C:\Users\Park MinJu\AppData\Local\Temp\ipykernel_18448\276879879.py:2: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[2.30258509,        nan,        nan],
       [3.80666249,        nan,        nan],
       [       nan,        nan,        nan],
       [2.19722458,        nan,        nan]])

In [135]:
np.log10(arr1)

C:\Users\Park MinJu\AppData\Local\Temp\ipykernel_18448\2590435965.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)


array([[1.        ,        nan,        nan],
       [1.65321251,        nan,        nan],
       [       nan,        nan,        nan],
       [0.95424251,        nan,        nan]])

In [136]:
np.log2(arr1)

C:\Users\Park MinJu\AppData\Local\Temp\ipykernel_18448\3085764489.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[3.32192809,        nan,        nan],
       [5.4918531 ,        nan,        nan],
       [       nan,        nan,        nan],
       [3.169925  ,        nan,        nan]])

In [137]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(arr1)

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1, -1, -1],
       [ 1, -1, -1]])

In [138]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr1)

array([[ 10., -88., -70.],
       [ 45., -34., -62.],
       [-14., -53., -41.],
       [  9., -26., -51.]])

In [139]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr1)

array([[ 10., -88., -70.],
       [ 45., -34., -62.],
       [-14., -53., -41.],
       [  9., -26., -51.]])

In [140]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [141]:
np.isnan(np.log(arr1))

C:\Users\Park MinJu\AppData\Local\Temp\ipykernel_18448\3789410203.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [142]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [143]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[-0.83907153,  0.99937328,  0.6333192 ],
       [ 0.52532199, -0.84857027,  0.67350716],
       [ 0.13673722, -0.91828279, -0.98733928],
       [-0.91113026,  0.64691932,  0.7421542 ]])

### 두개의 array 연산

In [154]:
#두 개의 array에 적용되는 함수

In [155]:
arr1

array([[ 10, -88, -70],
       [ 45, -34, -62],
       [-14, -53, -41],
       [  9, -26, -51]])

In [156]:
arr2 = np.random.randint(-100,100,size=(4,3)) #4행 3열로 난수 채움
arr2

array([[-76, -74,  16],
       [-32, -33,  28],
       [ 79,  62, -37],
       [ 36,   7,  81]])

In [157]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
np.multiply(arr1,arr2)

array([[ -760,  6512, -1120],
       [-1440,  1122, -1736],
       [-1106, -3286,  1517],
       [  324,  -182, -4131]])

In [158]:
arr1*arr2

array([[ -760,  6512, -1120],
       [-1440,  1122, -1736],
       [-1106, -3286,  1517],
       [  324,  -182, -4131]])

In [159]:
np.subtract(arr1,arr2)

array([[  86,  -14,  -86],
       [  77,   -1,  -90],
       [ -93, -115,   -4],
       [ -27,  -33, -132]])

In [160]:
arr1-arr2

array([[  86,  -14,  -86],
       [  77,   -1,  -90],
       [ -93, -115,   -4],
       [ -27,  -33, -132]])

In [161]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
np.maximum(arr1,arr2)

array([[ 10, -74,  16],
       [ 45, -33,  28],
       [ 79,  62, -37],
       [ 36,   7,  81]])

In [183]:
#통계함수

In [184]:
arr1

array([[ 10, -88, -70],
       [ 45, -34, -62],
       [-14, -53, -41],
       [  9, -26, -51]])

In [185]:
# 전체 성분의 합을 계산
np.sum(arr1)

-375

In [186]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-148,  -51, -108,  -68])

In [187]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([  50, -201, -224])

In [188]:
# 전체 성분의 평균을 계산
np.mean(arr1)

-31.25

In [189]:
# 행 간의 평균을 계산
np.mean(arr1, axis=0)

array([ 12.5 , -50.25, -56.  ])

In [190]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1)

36.62222685747004

In [191]:
np.min(arr1)

-88

In [192]:
np.min(arr1, axis=1)

array([-88, -62, -53, -51])

In [193]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1) # axis=none 일 경우 1차원 배열로 위치 파악

1

In [194]:
np.argmax(arr1)

3

In [196]:
np.argmax(arr1,axis=0) #행별 최대값

array([1, 3, 2], dtype=int64)

In [197]:
np.where(arr1>0)

(array([0, 1, 3], dtype=int64), array([0, 0, 0], dtype=int64))

In [198]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
np.cumsum(arr1)

array([  10,  -78, -148, -103, -137, -199, -213, -266, -307, -298, -324,
       -375], dtype=int32)

In [199]:
np.cumsum(arr1,axis=1)

array([[  10,  -78, -148],
       [  45,   11,  -51],
       [ -14,  -67, -108],
       [   9,  -17,  -68]], dtype=int32)

In [200]:
np.cumprod(arr1)

array([         10,        -880,       61600,     2772000,   -94248000,
        1548408704,  -202885376, -2131976960,  1511709440,   720483072,
       -1552690688,  1877813760], dtype=int32)

In [201]:
#np.where
x = np.array([5, 4, 3, 2, 1, 0])

In [202]:
np.where(x >= 3) #3과 같거나 큰값을 가지는 색인의 위치확인

(array([0, 1, 2], dtype=int64),)

In [203]:
x[np.where(x >= 3)] #조건에 맞는 값을 인덱싱하기

array([5, 4, 3])

In [204]:
##조건에 맞는 값을 특정 다른 값으로 변환하기
#배열의 값이 3과 같거나 크면 3으로 변환하고, 3보다 작으면 그대로 값을 유지
#(for loop & if else 조건문을 사용하는 것보다 수십배 빠르므로 매우 유용함)
np.where(x >= 3, 3, x)

array([3, 3, 3, 2, 1, 0])

In [205]:
x = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [218]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [219]:
np.where(x >= 6)

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [224]:
np.where(x >= 6, 0, x)

array([[1, 2, 3, 4],
       [5, 0, 0, 0],
       [0, 0, 0, 0]])

In [220]:
ids, cols = np.where(x >= 6) #3과 같거나 큰값을 가지는 색인의 위치확인

In [221]:
ids

array([1, 1, 1, 2, 2, 2, 2], dtype=int64)

In [222]:
cols

array([1, 2, 3, 0, 1, 2, 3], dtype=int64)

In [223]:
list(zip(ids, cols )) #같은 길이의 리스트를 같은 인덱스끼리 잘라서 리스트로 반환을 해주는 역할

[(1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]

In [212]:
result = list(zip(ids, cols )) #같은 길이의 리스트를 같은 인덱스끼리 잘라서 리스트로 반환을 해주는 역할

In [213]:
result

[(1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]

In [214]:
result[1][1]

2

### 정렬 함수

In [225]:
arr1

array([[ 10, -88, -70],
       [ 45, -34, -62],
       [-14, -53, -41],
       [  9, -26, -51]])

In [226]:
# 열 축 기준으로 오름차순 정렬(왼쪽에서 오른쪽으로)
np.sort(arr1)

array([[-88, -70,  10],
       [-62, -34,  45],
       [-53, -41, -14],
       [-51, -26,   9]])

In [227]:
# 행 축 기준으로 오름차순으로 정렬(위에서 아래로)
np.sort(arr1,axis=0)

array([[-14, -88, -70],
       [  9, -53, -62],
       [ 10, -34, -51],
       [ 45, -26, -41]])

In [228]:
# 행 축 기준으로 내림차순으로 정렬(위에서 아래로)
np.sort(arr1,axis=0)[::-1]

array([[ 45, -26, -41],
       [ 10, -34, -51],
       [  9, -53, -62],
       [-14, -88, -70]])

In [229]:
# 열 축 기준으로 오름차순 정렬(왼쪽에서 오른쪽으로)
np.sort(arr1,axis=1)

array([[-88, -70,  10],
       [-62, -34,  45],
       [-53, -41, -14],
       [-51, -26,   9]])

In [230]:
# 열 축 기준으로  내림차순으로 정렬(왼쪽에서 오른쪽으로)
np.sort(arr1,axis=1)[:,::-1]

array([[ 10, -70, -88],
       [ 45, -34, -62],
       [-14, -41, -53],
       [  9, -26, -51]])