# 함수 
### 함수의 활용

In [1]:
# 함수

In [2]:
def square(x):
    return x*x

In [3]:
square(3)

9

In [25]:
# 1분에 1m갈 수 있다고 할때 (s,d,는 km기준)
# 1000분에 1km
def myex(s,d):
    a= d-s
    time=1000*a
    hour = time//60
    min = time % 60
    return print("출발지에서 도착지까지 %d시간 %d분이 걸린다."%(hour,min))

In [26]:
myex(50,150)

출발지에서 도착지까지 100000시간 40분이 걸린다.


In [31]:
# 홀짝 구분
def even_or_odd(n):
    if n % 2 ==0:
        print("even")
        return
    print("odd")

In [32]:
even_or_odd(3)

odd


In [33]:
even_or_odd(4)

even


In [34]:
def Function_1(a,b):
    x=a+5
    y=b*3
    z=x+y
    return z

In [35]:
Function_1(1,5)

21

#### 입력변수가 몇개일지 모를때

In [36]:
# 누적합
def add_many(*args):
    result=0
    for i in args:
        result=result + i
    return result

In [39]:
add_many(1,5,1,44,6,2)

59

#### 여러 개의 입력값을 의미하는 *args 매개변수 앞에 choice 매개변수가 추가

In [40]:
def add_many(choice, *args):
    result=0
    if choice=="good":
        for i in args:
            result=result+i
    elif choice=="bad":
        for i in args:
            result=result-i
    return result

In [41]:
add_many("good",5,8,9,6,5)

33

In [44]:
# 딕셔너리 함수
def print_kwargs(**kwargs):
    print(kwargs)

In [45]:
print_kwargs(a=1)

{'a': 1}


In [46]:
print_kwargs(name="foo",age=3)

{'name': 'foo', 'age': 3}


In [63]:
def say_nick(nick):
    if nick=="바보":
        return
    print("나의 별명은 %s 입니다."%nick)

In [64]:
say_nick("바보")

In [65]:
say_nick("안녕")

나의 별명은 안녕 입니다.


#### T,F로 남녀 알려주는 함수

In [66]:
def say_myself(name,age,man=True):
    print("나의 이름은 %s 입니다."%name)
    print("나이는 %d살 입니다."%age)
    if man:
        print("성별은 남자입니다.")
        return
    print("성별은 여자입니다.")

In [67]:
say_myself("한소진",22,False)

나의 이름은 한소진 입니다.
나이는 22살 입니다.
성별은 여자입니다.


#### 함수 안에서 선언한 변수의 효력 범위

In [70]:
# (1)
a=1

def vartest(a):
    a=a+1
    print(a)

In [71]:
vartest(a)

2


In [72]:
a

1

In [73]:
#(2)
a=1

def vartest(a):
    a=a+1
    return a

In [74]:
vartest(a)

2

In [75]:
a

1

In [80]:
# (3): glabal명령어 사용-> 함수 내에서만 쓸 수 있는 변수가 아닌 밖에서도 함수에서 쓰는 변수들을 쓰고 싶은 경우
a=1
def vartest():
    global a
    a=a+1

In [81]:
vartest()

In [82]:
print(a)

2


In [94]:
def vartest(a):
    global b
    a = a+1
    b= a +11
    return b

In [95]:
vartest(1)

13

In [96]:
b

13

# Numpy 패키지
## Numpy 패키지 설치 및 import

In [83]:
# numpy 패키지 설치

In [84]:
#!pip install numpy

In [85]:
import numpy as np

## 배열 vs 리스트 비교

In [87]:
a = np.array([[1,2],[3,4]]) # array배열

In [89]:
a

array([[1, 2],
       [3, 4]])

In [97]:
b=[[1,2],[3,4]]

In [101]:
b

[[1, 2], [3, 4]]

In [107]:
a[1][1]

4

In [111]:
a[1,1]

4

In [113]:
b[1][1]

4

In [114]:
b[1,1]

TypeError: list indices must be integers or slices, not tuple

## 배열(array)만들기
### 1차원 배열

In [116]:
# Array 정의하기 및 사용

In [122]:
data1= [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [118]:
data2=[1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

#### numpy를 이용하여 array 정의하기
#### 1. 위에서 만든 python list를 이용

In [123]:
arr1=np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [126]:
# .shape사용해서 arr형태(크기)확인
arr1.shape

(5,)

#### 2. 바로 python list를 넣어줌으로써 만들기

In [128]:
arr2=np.array([1,2,3,4,5])
arr2.shape

(5,)

In [129]:
# .dtype : 자료형 확인
arr2.dtype

dtype('int32')

In [130]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [131]:
arr3.shape

(5,)

In [132]:
arr3.dtype

dtype('float64')

### 2차원 배열

In [133]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
arr4.shape

(4, 3)

In [136]:
arr4.dtype

dtype('int32')

In [140]:
type(arr4)

numpy.ndarray

### 3차원 배열

In [137]:
arr5 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

In [139]:
arr5.dtype

dtype('int32')

In [141]:
arr5.shape

(2, 4, 3)

In [143]:
type(arr5)

numpy.ndarray

### 기타 배열 만드는 함수

In [144]:
#np.zeros() -> 함수는 인자로 받는 크기만큼, 모든 요소가 0인 array를 만듬

In [145]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [147]:
np.zeros((3,5))[0,0]

0.0

In [148]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만듬

In [149]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [150]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [151]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만듬
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가짐

In [153]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [156]:
# np.full : (N, N) shape을 특정값으로 채움, (2,2)를 7로 채움
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [157]:
# np.eye : (N, N) shape의 단위 행렬(Unit Matrix)을 생성 / 대각행렬?
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [158]:
#초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성
#주의해야 할 것은 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어가 있음
np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.20749644e-320],
       [1.01855798e-312, 6.01346930e-154]])

In [162]:
# .reshape : array재배열 가능
# arange로 1부터 10 미만의 범위에서 1씩 증가하는 배열 생성
# 배열의 shape을 (3, 3)으로 지정
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
## np.--like()
np.ones(9).reshape(3,3)
np.ones_like(a)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [218]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [219]:
np.empty_like(a)

array([[      1,       0,       1],
       [      0,       0,       0],
       [      0,       0, 2949165]])

## Array 연산

In [232]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
arr1.shape

(2, 3)

In [198]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [199]:
arr2.shape

(2, 3)

In [200]:
#Array 덧셈
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [201]:
#Array 뺄셈
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [202]:
#Array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [203]:
#Array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 다른 크기의 array 연산

In [204]:
#arrar의 브로드 캐스트

In [233]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
arr1.shape

(2, 3)

In [240]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [241]:
arr3.shape 

(3,)

In [242]:
arr1 + arr3 #서로 다른 크기 연산가능. [10,11,12],[10,11,12]로 확장되어 계산

array([[11, 13, 15],
       [14, 16, 18]])

In [243]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [211]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

### Array 의 인덱싱

In [213]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
# 0번째 요소
arr1[0]

0

In [215]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [216]:
# 배열 인덱싱은 다차원 배열의 각 차원에 대해 가능
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [217]:
arr2[1,3]

8

In [221]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [224]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [226]:
# 모든 행의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

In [227]:
# 행의 순서 변경하기
arr2[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [228]:
# 열의 순서 변경하기
arr2[:,[3,2,0,1]]

array([[ 4,  3,  1,  2],
       [ 8,  7,  5,  6],
       [12, 11,  9, 10]])

### Array Boolean을 활용한 인덱싱

In [229]:
#Array Boolean 인덱싱

In [312]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4) #8행 4열로 난수 채움
data

array([[ 0.17132943,  2.41556674, -0.46357929, -1.64616497],
       [ 0.25471044, -0.60841117, -0.68291887, -0.7739267 ],
       [ 0.672681  , -0.83733101,  0.02645106, -1.54159541],
       [ 2.08894429, -0.41012802,  0.49307019, -0.48091679],
       [ 1.13833278, -0.36809985,  0.63795724,  1.67373762],
       [-0.87370769, -1.2712537 , -1.86097583,  0.57758808],
       [-0.40495052, -0.69955728,  0.18844386, -0.8348865 ],
       [-0.49304653,  1.73887532,  2.20154999, -0.45724185]])

In [314]:
np.round(data,3)

array([[ 0.171,  2.416, -0.464, -1.646],
       [ 0.255, -0.608, -0.683, -0.774],
       [ 0.673, -0.837,  0.026, -1.542],
       [ 2.089, -0.41 ,  0.493, -0.481],
       [ 1.138, -0.368,  0.638,  1.674],
       [-0.874, -1.271, -1.861,  0.578],
       [-0.405, -0.7  ,  0.188, -0.835],
       [-0.493,  1.739,  2.202, -0.457]])

In [245]:
# np.randeom.randint(지정값 사이에서의 정수를 원하는 형태로 만들어줌)
data=np.random.randint(0,100,size=(8,4))
data

array([[11, 76, 12, 15],
       [81, 58, 94, 40],
       [84, 97, 60, 35],
       [33, 35, 28, 25],
       [69, 95, 35, 73],
       [32, 22, 58, 42],
       [79, 86, 54, 13],
       [79, 27, 67, 86]])

In [248]:
type(data)

numpy.ndarray

In [249]:
data.shape

(8, 4)

In [251]:
data[:,0][data[:,0]<50]

array([11, 33, 32])

In [258]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 50보다 작은 행을 구한다.
data[data[:,0]<50,:]

array([[11, 76, 12, 15],
       [33, 35, 28, 25],
       [32, 22, 58, 42]])

In [268]:
# 0번째 열의 값이 50보다 작은 행의 2,3번째 열 값
data[data[:,0]<50,2:4]

array([[12, 15],
       [28, 25],
       [58, 42]])

In [273]:
#0번째 열의 값이 50보다 작은 행의 2,3번째 열값에 0을 대입
data[data[:,0]<50,2:4]=0
data

array([[11, 76,  0,  0],
       [81, 58, 94, 40],
       [84, 97, 60, 35],
       [33, 35,  0,  0],
       [69, 95, 35, 73],
       [32, 22,  0,  0],
       [79, 86, 54, 13],
       [79, 27, 67, 86]])

In [274]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [277]:
arr2[:,[True,False,False,True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [280]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [282]:
names[names=="Beomwoo"]

array(['Beomwoo', 'Beomwoo', 'Beomwoo', 'Beomwoo'], dtype='<U7')

In [284]:
data[names=="Beomwoo",:]

array([[11, 76,  0,  0],
       [81, 58, 94, 40],
       [32, 22,  0,  0],
       [79, 27, 67, 86]])

In [291]:
data[names=="Kim"]

array([[84, 97, 60, 35]])

In [293]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names=="Kim") | (names=="Park"),:]

array([[84, 97, 60, 35],
       [79, 86, 54, 13]])

## 연산에 활용하는 Numpy함수들

### 하나의 array에 적용

In [294]:
#하나의 arrary에 적용되는 함수

In [296]:
arr1 = np.random.randint(-100,100,size=(4,3))
arr1

array([[-71,  -8,  -8],
       [ 24, -46,  80],
       [-95,  13,  83],
       [ -6, -40,  22]])

In [297]:
# 각 성분의 절대값 계산하기 - np.abs
np.abs(arr1)

array([[71,  8,  8],
       [24, 46, 80],
       [95, 13, 83],
       [ 6, 40, 22]])

In [298]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

<ipython-input-298-1adcb47f53b6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[       nan,        nan,        nan],
       [4.89897949,        nan, 8.94427191],
       [       nan, 3.60555128, 9.11043358],
       [       nan,        nan, 4.69041576]])

In [299]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[5041,   64,   64],
       [ 576, 2116, 6400],
       [9025,  169, 6889],
       [  36, 1600,  484]], dtype=int32)

In [300]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr1)

array([[1.46248623e-31, 3.35462628e-04, 3.35462628e-04],
       [2.64891221e+10, 1.05306174e-20, 5.54062238e+34],
       [5.52108228e-42, 4.42413392e+05, 1.11286375e+36],
       [2.47875218e-03, 4.24835426e-18, 3.58491285e+09]])

In [301]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
np.log(arr1)

<ipython-input-301-bddc4320f0c3>:2: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[       nan,        nan,        nan],
       [3.17805383,        nan, 4.38202663],
       [       nan, 2.56494936, 4.41884061],
       [       nan,        nan, 3.09104245]])

In [302]:
np.log10(arr1)

<ipython-input-302-53e7f8b3389a>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)


array([[       nan,        nan,        nan],
       [1.38021124,        nan, 1.90308999],
       [       nan, 1.11394335, 1.91907809],
       [       nan,        nan, 1.34242268]])

In [303]:
np.log2(arr1)

<ipython-input-303-b8a38c33f7f8>:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[       nan,        nan,        nan],
       [4.5849625 ,        nan, 6.32192809],
       [       nan, 3.70043972, 6.37503943],
       [       nan,        nan, 4.45943162]])

In [306]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(arr1)

array([[-1, -1, -1],
       [ 1, -1,  1],
       [-1,  1,  1],
       [-1, -1,  1]])

In [307]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr1)

array([[-71.,  -8.,  -8.],
       [ 24., -46.,  80.],
       [-95.,  13.,  83.],
       [ -6., -40.,  22.]])

In [311]:
np.round(arr1)

array([[-71,  -8,  -8],
       [ 24, -46,  80],
       [-95,  13,  83],
       [ -6, -40,  22]])

In [315]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr1)

array([[-71.,  -8.,  -8.],
       [ 24., -46.,  80.],
       [-95.,  13.,  83.],
       [ -6., -40.,  22.]])

In [322]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [324]:
arr1[np.isnan(arr1)]

array([], dtype=int32)

In [325]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [326]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[-0.30902273, -0.14550003, -0.14550003],
       [ 0.42417901, -0.43217794, -0.11038724],
       [ 0.73017356,  0.90744678,  0.24954012],
       [ 0.96017029, -0.66693806, -0.99996083]])

### 두 개의 array 연산

In [327]:
#두 개의 array에 적용되는 함수

In [328]:
arr1

array([[-71,  -8,  -8],
       [ 24, -46,  80],
       [-95,  13,  83],
       [ -6, -40,  22]])

In [329]:
arr2 = np.random.randint(-100,100,size=(4,3)) #4행 3열로 난수 채움
arr2

array([[ 43, -47, -43],
       [ 82,   5,  54],
       [-33, -30,  29],
       [ 27,  77,  82]])

In [330]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
np.multiply(arr1,arr2)

array([[-3053,   376,   344],
       [ 1968,  -230,  4320],
       [ 3135,  -390,  2407],
       [ -162, -3080,  1804]])

In [331]:
arr1*arr2

array([[-3053,   376,   344],
       [ 1968,  -230,  4320],
       [ 3135,  -390,  2407],
       [ -162, -3080,  1804]])

In [332]:
np.subtract(arr1,arr2) # 빼기?

array([[-114,   39,   35],
       [ -58,  -51,   26],
       [ -62,   43,   54],
       [ -33, -117,  -60]])

In [333]:
arr1-arr2

array([[-114,   39,   35],
       [ -58,  -51,   26],
       [ -62,   43,   54],
       [ -33, -117,  -60]])

In [334]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
np.maximum(arr1,arr2)

array([[ 43,  -8,  -8],
       [ 82,   5,  80],
       [-33,  13,  83],
       [ 27,  77,  82]])

In [335]:
#통계함수

In [336]:
arr1

array([[-71,  -8,  -8],
       [ 24, -46,  80],
       [-95,  13,  83],
       [ -6, -40,  22]])

In [337]:
# 전체 성분의 합을 계산
np.sum(arr1)

-52

In [338]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-87,  58,   1, -24])

In [344]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([-148,  -81,  177])

In [342]:
np.mean(arr1,axis=0)

array([-37.  , -20.25,  44.25])

In [345]:
#np.where
x = np.array([5, 4, 3, 2, 1, 0])

In [346]:
np.where(x >= 3) #3과 같거나 큰값을 가지는 색인의 위치확인

(array([0, 1, 2], dtype=int64),)

In [347]:
x[np.where(x >= 3)] #조건에 맞는 값을 인덱싱하기

array([5, 4, 3])

In [348]:
x[x>=3]

array([5, 4, 3])